name: PHPStan

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --dev
      - name: Run analysis
        run: composer stan
